import os
import numpy as np
import pybullet as p
from gym_pybullet_drones.envs.BaseAviary import BaseAviary
from gym_pybullet_drones.utils.enums import DroneModel, Physics

class CustomDroneEnv(BaseAviary):
    def __init__(self, urdf_path="C:/path/to/export/world.urdf", **kwargs):
        self.urdf_path = urdf_path
        
        # Initialize default CF2X nano-quadcopter physics
        super().__init__(drone_model=DroneModel.CF2X, 
                         num_drones=1, 
                         physics=Physics.PYB, 
                         **kwargs)

    def _addObstacles(self):
        """Called automatically during env.reset() to spawn objects."""
        super()._addObstacles() # Loads the default ground plane
        
        if os.path.exists(self.urdf_path):
            # Load the custom world generated by your Blender script
            self.world_id = p.loadURDF(self.urdf_path, 
                                       basePosition=[0, 0, 0], 
                                       useFixedBase=True, 
                                       physicsClientId=self.CLIENT)
            print(f"[INFO] Loaded custom Blender world from {self.urdf_path}")
        else:
            print("[WARNING] No compiled URDF found. Spawning empty void.")

    # Mandatory Gym/Aviary Overrides (To be implemented by specific tasks)
    def _computeReward(self):
        raise NotImplementedError("Child classes must implement this to define custom reward functions.")

    def _computeTerminated(self):
        raise NotImplementedError("Child classes must implement this to define custom termination conditions.")

    def _computeTruncated(self):
        raise NotImplementedError("Child classes must implement this to define custom truncation conditions.")

    def _computeInfo(self):
        raise NotImplementedError("Child classes must implement this to define custom info dictionaries.")